name: Export Pre Release

on:
  push:
    branches: [ integration ]

jobs:
  # This workflow contains a single job called "build"
  export_pre_release:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.1
      with:
        fetch-depth: 0
    - name: export debug
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@v2.6.1
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2.3/mono/Godot_v3.2.3-stable_mono_linux_headless_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2.3/mono/Godot_v3.2.3-stable_mono_export_templates.tpz
        relative_project_path: ./
        export_debug: true
        generate_release_notes: true
        relative_export_path: ./export/debug
        create_release: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: export release
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@v2.6.1
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2.3/mono/Godot_v3.2.3-stable_mono_linux_headless_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2.3/mono/Godot_v3.2.3-stable_mono_export_templates.tpz
        relative_project_path: ./
        export_debug: false
        generate_release_notes: true
        relative_export_path: ./export/release
        create_release: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
